# Generated by Django 4.2.25 on 2025-11-03 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileBinary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('size', models.BigIntegerField(default=0)),
                ('content', models.FileField(upload_to=files.models.upload_path)),
                ('ref_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_filename', models.CharField(db_index=True, max_length=255)),
                ('file_type', models.CharField(db_index=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('binary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.filebinary')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_at'], name='files_file_uploade_726d10_idx'), models.Index(fields=['size'], name='files_file_size_6009e9_idx')],
            },
        ),
    ]
